[tool.black]
line-length = 79
target-version = ["py38"]
exclude = """
(
  /(
      /.git
    | /.github
    | /.pytest_cache
    | /.run
    | /.venv
    | /htmlcov
  )/
)
"""


[tool.isort]
force_single_line = true
line_length = 79
multi_line_output = 3
profile = "black"


[tool.pytest.ini_options]
console_output_style = "count"
filterwarnings = [
    "ignore::DeprecationWarning",
]
markers = [
]
testpaths = [
    "hw",
]
addopts = [
    "--cov",
    "--cov-report=html",
    "--cov-report=xml",
    "--numprocesses=auto",
]


[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
files = ["hw", ]
no_implicit_optional = true
pretty = true
python_version = "3.9"
show_error_context = true
sqlite_cache = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = [
    "asyncpg",
    "devtools",
    "freezegun",
    "uvicorn",
]
ignore_missing_imports = true


[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "R0801", # similar code
    "too-many-locals",
]
ignore = [
    ".github",
    ".mypy_cache",
    ".pytest_cache",
    ".run",
    ".venv",
    "__pycache__",
    "htmlcov",
]
jobs = 0
format = "colorized"
include-naming-hint = true
max-args = 12
max-line-length = 79
min-public-methods = 0
